server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.sql.init.platform=MySQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT
# jwtSecret should be at least 256 bits (32+ chars) for HS256.
ecommerce.app.jwtSecret=meghashakya235@gmail.com_this_is_a_perfect_secret_key
ecommerce.app.jwtExpirationMs=86400000

logging.level.com.ecommerce=INFO
logging.level.org.springframework.security=WARN
